[dependencies]
base = "0.14.14"
serde = "3.2.2"
sha2 = "0.1.4"
tweetnacl = "1.1.2"
map = "9.0.1"
prng = "0.0.5"
hash = "1.0.0"
new-base = "0.4.0"

[toolchain]
wasmtime = "25.0.1"
moc = "0.14.14"

[dev-dependencies]
bench = "1.0.0"
base64 = "1.0.1"
base-x-encoder = "1.2.0"
test = "2.1.1"
ic-certification = "https://github.com/f0i/ic-certification#main"
